# Generated by Django 3.1.7 on 2021-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('FR', 'French'), ('JP', 'Japanese'), ('EN-US', 'English'), ('CHI', 'Chinese')], default='JP', help_text='Language Name', max_length=5)),
            ],
        ),
    ]
